Serilog:
  MinimumLevel:
    Default: Debug
#    Override:
#      Microsoft: Warning
  WriteTo:
    - Name: Console
Yarp:
  Routes:
    - RouteId: r-module-master
      ClusterId: dapr-sidecar
      Match:
        Path: api/api1/{**catch-all}
      Metadata:
        Dapr: method
    - RouteId: r-module2-master
      ClusterId: dapr-sidecar
      Match:
        Path: api/api2/{**catch-all}
      Metadata:
        Dapr: method